module(name = "libyang", version = "1.0.73")

bazel_dep(name = "rules_cc", version = "0.2.10")
bazel_dep(name = "tar.bzl", version = "0.8.1")
# TODO(bazel-ready): Replace with tar 0.10.0 once it's released to the BCR.
git_override(
    module_name = "tar.bzl",
    commit = "9b76e660363ab2465d89d3aadbbc1f7afa02e65c",
    remote = "https://github.com/bazel-contrib/tar.bzl",
)
bazel_dep(name = "sonic-build-infra", version = "0.0.0", repo_name = "sonic_build_infra")
local_path_override(
    module_name = "sonic-build-infra",
    path = "../../sonic-net/sonic-build-infra",
)
bazel_dep(name = "rules_distroless", version = "0.0.0", repo_name = "rules_deb")
local_path_override(
    module_name = "rules_distroless",
    path = "../rules_distroless",
)

# Get pcre from Debian bookworm (libyang v1 uses PCRE, not PCRE2)
apt = use_extension("@rules_deb//apt:extensions.bzl", "apt")
apt.sources_list(
    architectures = ["amd64"],
    components = ["main"],
    suites = ["bookworm"],
    uris = ["https://snapshot.debian.org/archive/debian/20251001T023456Z"],
)
apt.install(
    dependency_set = "libyang_deps",
    suites = ["bookworm"],
    packages = [
        "libpcre3-dev",
        "swig",
        "python3-dev",
    ],
)
use_repo(apt, "libyang_deps")
